import enum

class Masks(enum.IntEnum):
    SID_MASK = 0xBF
    REPLY_MASK = 0x40

class DiagnosticSessionTypes(enum.IntEnum):
    DIAGNOSTIC_DEFAULT_SESSION = 0x01
    DIAGNOSTIC_PROGRAMMING_SESSION = 0x02
    DIAGNOSTIC_EXTENDED_SESSION = 0x03
    DIAGNOSTIC_SAFETY_SYSTEM_SESSION = 0x04
    
class ResponseCodes(enum.IntEnum):
    NEGATIVE_RESPONSE = 0x7F
    GENERAL_REJECT = 0x10
    SERVICE_NOT_SUPPORTED = 0x11
    SUBFUNCTION_NOT_SUPPORTED = 0x12
    INCORRECT_MESSAGE_LENGTH_OR_INVALIDAD_FORMAT = 0x13
    RESPONSE_TOO_LONG = 0x14
    BUSY_REPEAT_REQUEST = 0x21
    CONDITIONS_NOT_CORRECT = 0x22
    ROUTINE_NOT_COMPLETE =0x23
    REQUEST_SEQUENCE_ERROR =  0x24
    NO_RESPONSE_FROM_SUBNET_COMPONENT = 0x25
    FAILURE_PREVENTS_EXECUTION_OF_REQUESTED_ACTION = 0x26
    REQUEST_OUT_OF_RANGE = 0x31
    SECURITY_ACCESS_DENIED = 0x33
    INVALID_KEY = 0x35
    EXCEEDED_NUMBER_OF_ATTEMPTS = 0x36
    REQUIRED_TIME_DELAY_NOT_EXPIRED = 0x37
    DOWNLOAD_NOT_ACCEPTED = 0x40
    IMPROPER_DOWNLOAD_TIME = 0x41
    CANT_DOWNLOAD_TO_SPECIFIED_ADDRESS = 0x42
    CANT_DOWNLOAD_NUMBER_OF_BYTES_REQUESTED = 0x43
    UPLOAD_NOT_ACCEPTED = 0x50
    IMPROPER_UPLOAD_TYPE = 0x51
    CANT_UPLOAD_FROM_SPECIFIED_ADDRESS = 0x52
    CANT_UPLOAD_NUMBER_OF_BYTES_REQUESTED = 0x53

class AdditionalResponseCodes(enum.IntEnum):
    UPLOAD_DOWNLOAD_NOT_ACCEPTED = 0x70
    TRANSFER_DATA_SUSPENDED = 0x71
    GENERAL_PROGRAMMING_FAILURE = 0x72
    WRONG_BLOCK_SEQUENCE_COUNTER = 0x73
    ILLEGAL_ADDRESS_IN_BLOCK_TRANSFER = 0x74
    ILLEGAL_BYTE_COUNT_IN_BLOCK_TRANSFER = 0x75
    ILLEGAL_BLOCK_TRANSFER_TYPE = 0x76
    BLOCK_TRANSFER_DATA_CHECKSUM_ERROR = 0x77
    RESPONSE_PENDING = 0x78
    INCORRECT_BYTE_COUNT_DURING_BLOCK_TRANSFER = 0x79
    SUBFUNCTION_NOT_SUPPORTED_IN_ACTIVE_SESSION = 0x7E
    SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION = 0x7F
    SERVICE_NOT_SUPPORTED_IN_ACTIVE_DIAGNOSTIC_MODE = 0x80
    RPM_TOO_HIGH = 0x81
    RPM_TOO_LOW = 0x82
    ENGINE_IS_RUNNING = 0x83
    ENGINE_IS_NOT_RUNNING = 0x84
    ENGINE_RUN_TIME_TOO_LOW = 0x85
    TEMPERATURE_TOO_HIGH = 0x86
    TEMPERATURE_TOO_LOW = 0x87
    VEHICLE_SPEED_TOO_HIGH = 0x88
    VEHICLE_SPEED_TOO_LOW = 0x89
    THROTTLE_TOO_HIGH = 0x8A
    THROTTLE_TOO_LOW = 0x8B
    TRANSMISSION_RANGE_NOT_IN_NEUTRAL = 0x8C
    TRANSMISSION_RANGE_NOT_IN_GEAR = 0x8D
    BRAKE_SWITCH_NOT_CLOSED = 0x8F
    SHIFTER_LEVER_NOT_IN_PARK = 0x90
    TORQUE_CONVERTER_CLUTCH_LOCKED = 0x91
    VOLTAGE_TOO_HIGH = 0x92
    VOLTAGE_TOO_LOW = 0x93